version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: ubuntu:22.04
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./docker/nginx/templates:/etc/nginx/templates

  #MySQL Service
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: didakoo
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
